version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: sala_lilas_db
    environment:
      POSTGRES_USER: sala_lilas
      POSTGRES_PASSWORD: sala_lilas_pass
      POSTGRES_DB: sala_lilas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
